server:
  servlet:
    context-path: /root-context #as example

telegram:
  servlet:
    context-path: /telegram-bot
  brownie:
    token: ${test.token.value}
  example:
    token: ${test.token.value}
