server:
  port: 5000
#  ssl:
#    enabled: true
#    key-store-type: JKS
#    key-store: ${certificates.path}\pk_spring_boot.jks
#    key-store-password: ${certificate.password}
telegram:
  api:
    callback:
      proxy: ${public.host.ip4}
    bots:
      test:
        path: '/test'
        token: ${token.test}
